### ISSUE TITLE
Request: Please provide a package in Arch AUR

### ISSUE THREAD

**Issue by SpaceAgeHero** [optyfr/JRomManager#1]
Please provide (and maintain) a package in [Arch AUR](https://aur.archlinux.org/)

Thank you for JRomManager btw. Finally a powerful cross platform Rom Manager.

:-)

**Comment by optyfr** [comment]
Here is the package: https://aur.archlinux.org/packages/jrommanager/  
it may need upvoting to be included at least in community repository

BTW, since it's packaged, it does not know for what primary user it will be installed... even more it could be launched by different users on the same computer, so:
- it is installed in /usr/share/java/jrommanager with root:users ownership and 775 rights
- xmlfiles, cache, backup, ... dirs are still created in /usr/share/java/jrommanager but should be created instead in "$HOME/.jrommanager/"  
- jupdater may have trouble to update and need some extra work... or maybe should be auto disabled since update should be done via pacman

**Comment by optyfr** [comment]
JRomManager 1.6 is out, it has all options to be packaged, so I will update PKGBUILD accordingly before the end of this week

**Comment by optyfr** [comment]
PKGBUILD has been updated  
Program and libraries are installed in `/usr/share/java/jrommanager/`  
Launch script is `/usr/bin/jrommanager`  
The working files are now located at `$HOME/.jrommanager/` so you will have to manually move directories `xmlfiles`, `settings`, `cache`, and `report` there...  
There is also a desktop icon (with category set to utility)
Please test it and tell me if it's OK for you

**Comment by SpaceAgeHero** [comment]
Upgraded the package and made some multithreaded scans. So far everything seems fine.
Thanks again.

Hope you don't mind I've advertised JRomManager here a little bit:
https://www.reddit.com/r/emulation/comments/8xxvd6/jrommanager_open_source_cross_platform/

**Comment by optyfr** [comment]
No problem, but in regards of some critics, I'll have to sign up ;-p
