### ISSUE TITLE
DEMUL emulator DAT (XML): Scanner wrongly reports bad CRC for values with leading spaces instead of leading 0

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#132]
Hey @optyfr!
Could you please have a look at DEMUL's DAT?
[demul07_280418 DAT (XML).zip](https://github.com/optyfr/JRomManager/files/7453167/demul07_280418.DAT.XML.zip)

JRomManager reports bad roms because, I think, it cannot understand the starting zero in the CRC value...

See image
![DEMUL wrong CRC (0x)](https://user-images.githubusercontent.com/65762930/139670892-5b1285cb-f605-4dd0-9a06-58bcfd89db9d.jpg)

Is it fiìxable?

**Comment by optyfr** [comment]
Not a problem of 0x as you can see hereunder... but an empty space problem at start of some CRC value (leading 0 replaced with spaces), that should be probably fixable, but in the meantime and because there is not only CRC in this dat but also SHA1, this should work ok if you select the option "calculate all SHA1"
![image](https://user-images.githubusercontent.com/17027109/139684756-0db3436b-f2e6-4059-9d84-b64111b9db42.png)

**Comment by cinnamonmatexfce** [comment]
Fine! ;) Ok, giving that only issue I had is with DEMUL's DAT and it is no a big deal scanning with _Calculate all SHA1_, I'm closing this issue.
