### ISSUE TITLE
Missing Images on GUI on server mode

### ISSUE THREAD

**Issue by juan-fuentes-sis** [optyfr/JRomManager#188]
JRomManager seems to run well on Synology DSM7, what makes it a great option to not rely on a separate VM to run software.

Sadly the current version doesn't seem to point to the images correctly.

I was also able to reproduce this problem under Ubuntu.

**Comment by optyfr** [comment]
What package did you use to run on synology? I need to understand
What the "current version" for you?
I will create a new beta soon for 3.0, there have been a lot of work on the server version recently...

**Comment by juan-fuentes-sis** [comment]
Latest 2.5.x , I was worried 3 was not stable.

I just copied it and started it manually from the console. Using JDK11 from syno comunity.

Now a native syno comunity package would be a great idea. I would support that.

**Comment by optyfr** [comment]
2.5 is old story, too much has changed since then
Question : Do JDK 17 exists for Synology?
Even "native", JDK will be needed at a certain point : 
- either for compîling the native executable with a special jdk like GraalVM (but it's still very experimental and very problematic with reflection), 
- either bundled for running as actually for debian or as an appimage

The most immediate solution to come, is the zip package version and an already existing jdk 17 installed, because I'm working on systemd install script for server running in that version

**Comment by juan-fuentes-sis** [comment]
I don't think JDK17 exists yet but since is x86 and there is already a JDK11 available it should not be a big deal. 

If not packaging the JDK with JRomManager should be doable too.

Any solution is better than Docker since Synology CPUs tend to be under powered.

**Comment by optyfr** [comment]
if your synology processor is 64 bits then try appimage version maybe?

**Comment by juan-fuentes-sis** [comment]
It comes with 8GB of ram so I would expect 64bits. As soon as the next 3.0beta is released I can retest everything I encountered.

**Comment by optyfr** [comment]
It's released

**Comment by juan-fuentes-sis** [comment]
On 3.0 the web interface works properly, no missing images.

**Comment by juan-fuentes-sis** [comment]
Regarding support for Synology I started to look into making a native JDK17 package so I gain experience that allow me to also make a JRomcenter package.

If I archive that goal people with 32tb to 128tb collections would probably start considering it if multi dat processing is added.
