### ISSUE TITLE
Report shows missing files with hide missing enabled

### ISSUE THREAD

**Issue by juan-fuentes-sis** [optyfr/JRomManager#191]
Can't remember exactly the steps to reproduce now.

**Comment by juan-fuentes-sis** [comment]
Latest 2.5.x , I was worried 3 was not stable.

**Comment by optyfr** [comment]
ok this will need to be reevaluated in 3.0

**Comment by juan-fuentes-sis** [comment]
I started 3.0 on ubuntu desktop and got server mode started by default. Could not get the desktop gui started to test this.

**Comment by optyfr** [comment]
If you use noarch you will only get cli/server version, if you use x86_64 version then you will get cli/server + desktop version... and it should open by default... This is because javafx is hardware dependent (it needs extra native libraries)
Of course, if you used an x86_64 and it started server mode, then that's not normal

**Comment by juan-fuentes-sis** [comment]
Personally I prefer to not have an installer so I picked the zip.

https://github.com/optyfr/JRomManager/releases/download/3.0.0-beta.4/JRomManager-3.0.0.zip

I have now tried the AppImage and indeed it shows the JavaFX UI by default.

**Comment by optyfr** [comment]
So does it work with 3.0?
