### ISSUE TITLE
JRomManager crashes when fixing existing Torrent7Z (RomVault) sets

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#27]
Hi optyfr!
As in title.
I've got all my roms parsed with https://www.romvault.com/trrntzip/download/TrrntZipUI262.zip using Trrntzip (`mono TrrntZipUI.exe`) to fix and compress in 7z format.
Then I've done a check with JRomManager.

I'm using: https://aur.archlinux.org/packages/jrommanager-bin/
 'extra/p7zip 16.02-6' is installed

Scanner ---> Settings (enabled options):
> Enable MultiThreading
> Create missing sets
> Use implicit merge
> Exclude machines
> Compression: 7Zip archive
> Merge Mode: Non Merged (including BIOS and Devices)

JRomManager ---> Settings --> Compressors:
> Zip ---> Temporary files threshold: Above 10MB
> Zip ---> Compression Level: STORE method
> Zip (external) ---> Path to command: /usr/bin/7z
> Zip (external) ---> Compression Level: STORE method
> Zip (external) ---> Threads: 1
> 7z (external) ---> Path to command: /usr/bin/7z
> 7z (external) ---> Compression Level: STORE method
> 7z (external) ---> Threads: 16
> 7z (external) ---> Solid archive: yes

No strange errors in bash output.

Here's to you: logs and screenshot.

[JRM_logs.zip](https://github.com/optyfr/JRomManager/files/4675924/JRM_logs.zip)
![JRomManager, Scanner, Report](https://user-images.githubusercontent.com/65762930/82790901-22c23c00-9e6d-11ea-8bb3-feb22e4b1f25.jpeg)

**Comment by optyfr** [comment]
Some remarks :

1. external 7z won't be used for 7z compression since sevenzipjbinding is supported for your platform, so compression is a native lib, and p7zip is not needed at all
2. STORE won't compress anything and is near to zero interest with solid mode, I'm not even sure that STORE and solid are valid combinations in fact...
3. Can you kill and retry? with linux native look&feel from java, sometimes interface locks up while showing progress, it seems to be a java swing bug encountered only with linux, in that case the preferred way is to use server mode with a browser (until I find a way to circumvent this problem)
4. If you intend only to recompress, then use compress batch tool ;-)

**Comment by cinnamonmatexfce** [comment]
1. Is sevenzipjbinding supported and in-use even if I installed the `-bin` version?
2. I'm doing some tests, and that's why I'm using STORE mode (I need to be fast); when roms are in a good shape, then I found that MAXIMUM is -  for me - a good tradeoff between size and speed.
3. I'll try ASAP (maybe in the next weekend, but I hope sooner)
4. Can I use the "Batch" to recompress with Torrent7Z and setting my desired level of 7Z compression?

Here's some (rough) compression tests:
[JRomManager_compressor_tests.txt](https://github.com/optyfr/JRomManager/files/4678754/JRomManager_compressor_tests.txt)

**Comment by optyfr** [comment]
1. Yes, the only case when it's not used is for exotic OSes on exotic CPU architectures
2. OK, also please check that you t7z files are not corrupted
3. OK, if it's not locked then you should get at least an exception in bash output, and/or error message, and/or app quit
4. Batch is dedicated for recompression (no rom fix or archive structure manipulation), it will use the global setting for compression mode (if not, then it's a bug!)

**Comment by optyfr** [comment]
I don't know if you managed to reproduce the crash, but on my side, I made crash the java virtual machine with jrommanager, and it was simply due to an out of memory...

**Comment by cinnamonmatexfce** [comment]
>but on my side, I made crash the java virtual machine with jrommanager, and it was simply due to an out of memory...
>
Could be issues of out-of-memory even with 16GB of RAM?
</br>

> I don't know if you managed to reproduce the crash
>
I cannot reproduce the crash because I cannot reproduce the same exact environment: I converted all of my ROMs into normal ZIP files (nor 7Z, neither Torrent7Z) and - for the moment - I have no space left on my HDDs.
Btw, hope this little test is worth for your debugging:

1. copied 4GB or ZIP ROMs
2. then converted all from normal ZIP to Torrent7Z
3. then SCAN+FIX JRomManager: no issues this time!
</br>

> Some remarks :
> 
>     3. Can you kill and retry? with linux native look&feel from java, sometimes interface locks up while showing progress, it seems to be a java swing bug encountered only with linux, in that case the preferred way is to use server mode with a browser (until I find a way to circumvent this problem)
> 
See #29

**Comment by cinnamonmatexfce** [comment]
>     2. OK, also please check that you t7z files are not corrupted
> 
I can speak for the test (see my comment above): the Torrent7Z files I fixed with JRomManager are all healthy

**Comment by optyfr** [comment]
Are you sure that torrentzip.net is really producing t7z files? seems to be classic 7z files (I can't see any extra data for checksuming while using it)... anyway, even with 16GB, the launch script will default limit the JVM to 2GB (look in /usr/bin/jrommanager launch file) for small devices, if you want more => cp this launch file in /usr/bin to another name and modify the copy from 2G to more
Memory consumption, also depends of compression level, Normal compression will need 1,3GB of memory *per processed archive* (and you have many cores), while ULTRA mode will need at least 5GB of memory!!! Furthermore Solid archive is a real pain because you need to recompress the entire archive each time you add or remove a small file in the archive, that's the way 7zip is made and it is not recommended for manipulating archives, but just for final archiving...

**Comment by cinnamonmatexfce** [comment]
>Are you sure that torrentzip.net is really producing t7z files?
>
You mean when I use `$ mono TrrntZipUI.exe`?
Mmm... Looking at the romfiles inside T7Z, there is NO "_TORRENTZIPPED-nnnnAAAA_" comment.
Ok, I'll leave all my roms simply ZIP compressed, not a big issue! ;)
</br>
> if you want more => cp this launch file in /usr/bin to another name and modify the copy from 2G to more
>
You mean by changing both line `OPT=-Xmx2g` into `OPT=-Xmx8g` (if I want to address 8GB of RAM) and line `OPT=-xmx2g` into `OPT=-xmx8g`? Ok, I'll try that.
</br>
> Furthermore Solid archive is a real pain because you need to recompress the entire archive each time you add or remove a small file in the archive, that's the way 7zip is made and it is not recommended for manipulating archives, but just for final archiving...
>
In fact I DON't want solid archives; but if I uncheck that option, I CANNOT set the compression level...
</br>
@optyfr you can close this issue, if you don't mind. Thanks for you time! ;)

**Comment by optyfr** [comment]
Yes, I meant using TrrntZIPUI via mono, it's indeed not t7z but 7z, t7z has been officially abandoned rv7z may replace it but it's not yet official nor recognized

Yes, -Xmx8g, but regarding the number of threads, that would be not enough for 7z... please also note that 2GB should be enough when using zip or tzip because only a few MB of memory is needed for compressing one archive file, decompressing 7z is also not very consuming, juste 7z compression is extreme

I have disabled compression level when solid is disabled because sevenzipjbinding was not taking into account the compression level in solid mode, it was certainly a bug in that library, but now that a new version has appeared, I will check again if this behavior did change, and re-enable it for the next minor release if possible...
