### ISSUE TITLE
Server Mode is broken since optyfr/jrommanager:3.0.0-beta.13

### ISSUE THREAD

**Issue by L4R5** [optyfr/JRomManager#277]
I tried the server mode using the docker container. Since optyfr/jrommanager:3.0.0-beta.13 it prints out the following error message after opening the server url in a web browser

[logs.txt](https://github.com/user-attachments/files/15801296/logs.txt)

**Comment by optyfr** [comment]
There seems to be a bug in Jetty 12 for some specific use case :
- when resource as a gzip precompressed version to serve
- when resource is also in a jar file archive
- when this jar is served as a ResourceURL

The bug is still there for jetty 12.0.8, I have to try with latest 12.0.10

if it's still present, I will create an issue for jetty team and after this, here is the solutions possible :
- wait for issue to be resolved and released (may be long)
- disable precompressed headers in the hope that there is no other etag problem elsewhere (fast resolution but not guaranteed and will slow down loading)
- step back to jetty 11 (big work, not desired)

**Comment by optyfr** [comment]
https://github.com/jetty/jetty.project/issues/11925

**Comment by optyfr** [comment]
fixed in release 3.0.4
