### ISSUE TITLE
unRAR license

### ISSUE THREAD

**Issue by ghost** [optyfr/JRomManager#3]
I'd like to try JRomManager on my Gentoo system, but I'm worried about the unRAR license I need to allow in order to emerge it. Is there a way to avoid that? Is that part optional or mandatory? Thanks.

**Comment by optyfr** [comment]
In fact unrar is currently not even used! But it's part of 7zipjbinding, and removing 7zjbinding would make 7z handling very inefficient (call to 7z cmd line needed for each 7z archive operation), so I made it mandatory...  
  
Furthermore, you have to know that emerging jrommanager will not compile anything because gradle is not supported by gentoo's portage, so it's simply java binary dist zip archive extraction, and so you could theorically remove 7zjbinding by removing  sevenzipjbinding-AllPlatforms.jar afterward (and so after having accepted unrar licensing)...  
  
BTW, I do not retrieve anywhere on the 7zip site the UnRAR license needing (despite unrar support), so it may not finally be needed at all (or anymore?). And I also do not see anywhere in 7zipjbinding unrar license (it's just LGPL)  
  
Also, you may want to recompile yourself outside portagee, if so just follow the compilation instructions [here](https://github.com/optyfr/JRomManager/blob/master/README.md) and adjust maven import to not include sevenzipjbinding dlls by replacing:  
compile group: 'net.sf.sevenzipjbinding', name: 'sevenzipjbinding-all-platforms', version: '9.20-2.00beta'  
with  
compile group: 'net.sf.sevenzipjbinding', name: 'sevenzipjbinding', version: '9.20-2.00beta'

**Comment by optyfr** [comment]
Here is the exact license terms for sevenzipjbinding: https://github.com/borisbrodski/sevenzipjbinding/blob/master/License.txt
So the unrar restriction mean that you must agree that you'll not use unrar code to make a rar compressor
