### ISSUE TITLE
open JRomManager?

### ISSUE THREAD

**Issue by therock40359** [optyfr/JRomManager#36]
i am kind of new to Ubuntu and i do like it better than windows but i've got a lot to learn.  i am trying to run the JRomManager on ubuntu 20 and i followed your instructions via the readme.md.
i do not know how to run the program once it is installed could you please give me some advice

First, you need OpenJDK 11 installed from your system package manager or from the official installer, or at least take care that all java jdk binaries are accessible from your current $PATH or %PATH%

    [Optional] If your are on Windows, and you want to build the MSI installer, you'll need
        the latest WIX Toolset to be installed and its bin/ folder added in your %PATH%
        OpenJDK 14 installed (for jpackage)

Download and unarchive https://github.com/optyfr/JRomManager/releases/download/<version>/JRomManager-<version>-src.tgz (use sevenzip for Windows); Do not download Source Code (zip) or Source Code (tar.gz), those ones are automatically built by github and unfortunately does not contains required submodules
cd JRomManager-<version>
run

    Unix: sh ./gradlew build

**Comment by optyfr** [comment]
This was the instruction on how to compile and packaging, it won't be installed, you will need extra step from that... but since there is a .deb package available on github's releases section (and because ubuntu is  debian based), you should directly install it this way, then you will get an icon available to launch in your menu, it will be installed in /opt and should be accessible in your search path...
here is the instructions on how to install : https://help.ubuntu.com/kubuntu/desktopguide/C/manual-install.html
