### ISSUE TITLE
Softwarelist incomplet?

### ISSUE THREAD

**Issue by sgerum** [optyfr/JRomManager#4]
Hi,
can you please check softwarelist? I have a problem. The directory advantage was deleted by jrommanager, but there is a hash file advantage.xml in the hash dir of mame. Jrommanager says that this dir is not necessary.
I think 11 dirs were deleted.

Regards,
 Sven

**Comment by optyfr** [comment]
Hi,
Did you import software list from mame executable? If so, that's normal since mame software list export function will exclude some not yet supported software lists (even if it's in the hash directory), that means that you can't play those roms with mame yet because there is no working emulation for those machines  

2 solutions:
- check "ignore unknown files" to not delete extra dirs and you will have to handle these extras unsupported xml as independent profiles
- To handle ALL software lists, use the Dir Updater batch tool (available from v1.8) and drop directly the mame hash directory in the first column, drop your software list base directory in the second one, choose TZIP (same as zip with extra comments in it) preset, then click "Start" to update. (test with dry run first).. but be careful this preset will do only split because it was originally made for dir2dat dats files  

I'll add more presets in dir updater batch tool for the next version and you will be able to chose same options than in individual profile scanning

**Comment by sgerum** [comment]
Hi,
ok, you are right. Import comes from mame binary.
I check your solution after restore :-)
Thank you.
Sven
