### ISSUE TITLE
Import Dat / Software list not opening file dialog

### ISSUE THREAD

**Issue by nilsbyte** [optyfr/JRomManager#42]
I am on macOS 11.1 Big Sur and the file dialog for 'Import Dat' or 'Import software list' only shows one time. If i try it the second time, the dialog does not appear and the application freezes. I have to reboot the Mac to be able to open the dialog again, but it still works only one time.

Installed Java Version is 8 Update 271 (Build 1.8.0_271-b09)

**Comment by optyfr** [comment]
You didn't tell what you've done in between, neither the software version
Anyway, too much things were rewritten since latest stable, please use latest 2.5 beta with Java 11 or better
Please also note that I won't be able to release any DMG by myself anymore, because I don't have a Mac, so you'll have to use the zip archive version (help needed)
I will close this issue, please feel free to open another issue if it still happen

**Comment by nilsbyte** [comment]
What do you think which version I used? Of course the newest. `JRomManager-2.4.4-install.jar`
And if I had done other steps in between in would have mentioned it.

1. Install
2. Start JRomManager
3. Click on "Import Dat"
4. File Dialog opens (can't access certain folders on the Mac, btw)
5. Directly after that, if i click "Import Dat" again, the button freezes the whole App
6. Stays that way, even when I relaunch JRomManager, until I reboot the Mac

UPDATE for 6: Now the button doesn't work at all, even after reinstalling JRomManager

P.S. I try to help here, so a bit more cooperation is appreciated.

**Comment by nilsbyte** [comment]
FYI: With 2.5.0 and openJDK 11 it seems to be resolved.
