### ISSUE TITLE
[REQUEST] systemd service

### ISSUE THREAD

**Issue by RibShark** [optyfr/JRomManager#45]
It would be nice to have a systemd service file for the server  and full server modes included with the .deb installation so JRomManager can be started/stopped via systemctl and other tools. I could not find launcher.sh with this installation.

**Comment by optyfr** [comment]
Since 2.5.0, Tanuki service wrapper and its launcher script is available **only** in noarch.rpm/all.deb versions. Launcher script has install mode which support systemd (but you may need to hack the script if your linux distrib is not recognized as supporting systemd). Be careful, 2.5.0 is still beta and not very well tested yet with launcher script...
If you were using 2.4.x, then launcher script should be located in /opt/jrommanager/wrapper/bin subdir whatever the distrib package used

**Comment by RibShark** [comment]
Ah, OK, I needed to install the all.deb version. Is there any way to use full server mode (w/ password/users) with the service wrapper?

**Comment by optyfr** [comment]
@RibShark since I can't know where you want to set your work dir nor the cert path for FullServer, you'll have to edit /opt/jrommanager/wrapper/conf/wrapper.conf and change all wrapper.app.parameter.X according your flavor and with the help of the wiki page [here](https://github.com/optyfr/JRomManager/wiki/Full-Server-mode#server-mode)
