### ISSUE TITLE
Installing as service fails on Raspberry Pi OS x64

### ISSUE THREAD

**Issue by SpaceAgeHero** [optyfr/JRomManager#46]
Hi Opty,
tested Simple Server mode on my Raspberry Pi 4 and it's working fine, except that I can't get 7z compression running.
Anyways I'd like to install the service as mentioned in your Wiki but I get this error:

> pi@raspberrypi:/opt/jrommanager/wrapper/bin $ sudo ./launcher.sh installstart
Unable to locate any of the following binaries:
  /opt/jrommanager/wrapper/bin/./wrapper-linux-aarch64-
  /opt/jrommanager/wrapper/bin/./wrapper-linux-aarch64-32
  /opt/jrommanager/wrapper/bin/./wrapper

**Comment by optyfr** [comment]
Hi,
JRomManager is using tanuki java service wrapper, the current version bundled was 3.5.37, but aarch64 is only supported from 3..5.38 (current version is 3.5.45)! If you want it immediately, then download it [here](https://download.tanukisoftware.com/wrapper/3.5.45/wrapper-delta-pack-3.5.45.zip) and replace my files in wrapper folder, you'll also need to adapt/update (but not fully replace) my launcher.sh script with code from src/bin/sh.script.in
If you succeeded I'm interested in getting your script to build 2.5.0 beta 3 (or maybe release it as final) because I've unfortunately no time to seriously work on JRomManager at the moment...

**Comment by optyfr** [comment]
I upgraded to 3.5.45 and adapted the script *but* did not test it all, it'll be released soon in beta 3, don't hesitate to tell me if it works or not
